# Site settings
title: "KhanhCM Porfolio"
description: "KhanhCM Porfolio"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chau Minh Khanh"
resume_title:                   "Penetration Tester | Red Teamer | Security Analyst | Security Bug Bounty Hunter"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "khanhcm@proton.me"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "Contact"
resume_contact_address:         "Vietnam"

resume_header_contact_info:     "Vietnam • khanhcm@proton.me"
display_header_contact_info:    "false"

resume_header_intro: "<p>👋 Hi everyone, my name is Chau Minh Khanh.</br></br>I am an experienced Security Engineer with a demonstrated history of working in the Information Security industry and skilled in Penetration Testing, Vulnerability Assessment and Red Teaming. I am interested in finding and reporting security vulnerabilities through Bug Bounty and Responsible Disclosure Programs. I desire to learn, practice, and develop in-depth skills in the field of information security in a professional environment.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/khanhchauminh"
  # resume_twitter_url:           "#"
  # resume_dribbble_url:          "#"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/khanhcm"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://khanhcm.medium.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
